services:
    datasource:
        image: 'postgres:bookworm'
        env_file:
            - '.envs/datasource.env'
        ports:
            - '5432:5432'
        volumes:
            - 'datasource:/var/lib/postgresql/data'
        networks:
          - 'backend'

    app:
        image: 'ghcr.io/tired-donut/post-it-backend/post-it-backend'
        env_file: '.envs/app.env'
        ports:
            - '3000:3000'
        networks:
           - 'router'
           - 'backend'
        labels:
           - 'traefik.enable=true'
           - 'traefik.docker.network=router'
           - 'traefik.http.routers.post-it-backend.rule=Host(`backend.post-it.webshrimps.cc`)'
           - 'traefik.http.routers.post-it-backend.entrypoints=websecure'
           - 'traefik.http.routers.post-it-backend.tls.certresolver=resolver'
           - 'traefik.http.services.post-it-backend.loadbalancer.server.port=3000'

networks:
  backend:
    driver: 'overlay'
    name: 'backend'
  router:
    external: true

volumes:
    datasource:
        driver: 'local'
