services:
    datasource:
        image: 'postgres:bookworm'
        environment:
            - 'POSTGRES_USER=${DATABASE_USERNAME}'
            - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
            - 'POSTGRES_DB=${DATABASE_NAME}'
        ports:
            - '${DATABASE_PORT}:5432'
        volumes:
            - '${DATABASE_STORAGE_PATH}:/var/lib/postgresql/data'

    app:
        build: .
        environment:
            - 'APP_HOST=0.0.0.0'
            - 'APP_PORT=3000'
            - 'DATABASE_HOST=datasource'
            - 'DATABASE_PORT=5432'
            - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
            - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
            - 'DATABASE_NAME=${DATABASE_NAME}'
            - 'TOKEN_SECRET=${TOKEN_SECRET}'
        ports:
            - '3000:3000'
