services:
    database:
        image: 'postgres:bookworm'
        environment:
            - 'POSTGRES_USER=${DATABASE_USERNAME}'
            - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
            - 'POSTGRES_DB=${DATABASE_NAME}'
        ports:
            - '${DATABASE_PORT}:5432'
        volumes:
            - './storage:/var/lib/postgresql/data'
