services:
    datasource:
        image: 'postgres:bookworm'
        env_file:
            - '.envs/datasource.env'
        ports:
            - '5432:5432'
        volumes:
            - 'datasource_volume:/var/lib/postgresql/data'
        restart: 'unless-stopped'

    app:
        image: 'ghcr.io/tired-donut/post-it-backend/post-it-backend'
        env_file: '.envs/app.env'
        ports:
            - '3000:3000'
        restart: 'unless-stopped'

volumes:
    datasource_volume:
        driver: 'local'
