name: Main

on:
    push:
        branches:
            - main

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build application
              run: |
                  docker build -t ghcr.io/tired-donut/post-it-backend/post-it-backend .

            - name: Log in registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.REGISTRY_USER }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Push image to registry
              run: |
                  docker push ghcr.io/tired-donut/post-it-backend/post-it-backend

            - name: Export stack configuration
              uses: actions/upload-artifact@v4
              with:
                  name: docker-stack
                  path: docker-compose.yaml

    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Import stack configuration
              uses: actions/download-artifact@v4
              with:
                  name: docker-stack

            - name: Set up ssh key
              run: |
                  echo "${{ secrets.SSH_KEY }}" >> ssh_key
                  chmod 600 ssh_key

            - name: Copy stack configuration
              run: |
                  scp -i ssh_key -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.STACK_PATH }}/${{ secrets.STACK_FILE }}

            - name: Deploy application
              run: |
                  ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
                    docker stack deploy -c ${{ secrets.STACK_PATH }}/${{ secrets.STACK_FILE }} --prune ${{ secrets.STACK_NAME }}
                  "
